/**
 * ApiKey (Sprint 9 - implemented).
 *
 * PURPOSE
 *   A tenant-scoped, revocable credential for the external API surface
 *   (`X-Api-Key`). Each key carries a set of read-only scopes that bound
 *   what the external caller may query, plus an optional expiry. The full
 *   secret is shown to the caller exactly once at creation; only a
 *   SHA-256 hash of the secret and a public `prefix` are persisted so a
 *   database leak cannot be replayed.
 *
 * SECURITY CONTRACT
 *   - The secret is a 256-bit URL-safe random value generated by
 *     `utils/encryption`-style `crypto.randomBytes` (see `apiKey.service`).
 *   - `secretHash` = SHA-256(secret). SHA-256 (rather than a slow KDF) is
 *     correct here because the input is already high entropy; a KDF would
 *     only add latency to every external request without raising the
 *     attack cost.
 *   - `prefix` (e.g. `sak_ab12cd34...`) is the lookup key used to find the
 *     record before verifying the hash, so an invalid key fails fast and
 *     valid keys are never compared against every row.
 *   - `scopes` are an allow-list: unknown scopes are rejected at creation
 *     and never silently broadened.
 *
 * LIFECYCLE
 *   `active` keys may be queried until `expiresAt` (null = never). A key
 *   is `revoked` explicitly (revocation is permanent) or soft-deleted;
 *   expiry is computed on read, it does not mutate the document.
 *
 * PLUGINS
 *   tenantScope, softDelete, paginate, optimisticConcurrency, audit
 *   (module `api_keys`).
 *
 * INDEXES
 *   - unique(prefix) sparse
 *   - { tenantId: 1, status: 1 }
 */

import mongoose from 'mongoose';
import { tenantScope, softDelete, paginate, optimisticConcurrency, audit } from './plugins/index.js';

export const MODEL_NAME = 'ApiKey';

/** Scopes an API key may carry (read-only, allow-listed at creation). */
export const API_KEY_SCOPES = Object.freeze([
  'analytics:query',
  'datasets:read',
  'connectors:read',
  'dashboards:read',
]);

export const API_KEY_STATUSES = Object.freeze(['active', 'revoked']);

export const API_KEY_LIMITS = Object.freeze({
  NAME_MAX: 120,
  REVOKE_REASON_MAX: 500,
});

const apiKeySchema = new mongoose.Schema(
  {
    tenantId: { type: String, required: true, index: true },
    name: { type: String, required: true, trim: true, maxlength: API_KEY_LIMITS.NAME_MAX },
    // Public lookup prefix (e.g. `sak_<random>`); unique so lookups by
    // prefix are a single indexed read.
    prefix: { type: String, required: true, unique: true, index: true },
    // SHA-256 of the full secret. Never stored or returned in plaintext.
    secretHash: { type: String, required: true },
    scopes: {
      type: [String],
      required: true,
      validate: {
        validator: (values) =>
          Array.isArray(values) &&
          values.length > 0 &&
          values.every((v) => API_KEY_SCOPES.includes(v)),
        message: `scopes must be a non-empty subset of ${API_KEY_SCOPES.join(', ')}`,
      },
    },
    // null = never expires.
    expiresAt: { type: Date, default: null },
    lastUsedAt: { type: Date, default: null },
    status: { type: String, enum: [...API_KEY_STATUSES], default: 'active', index: true },
    revokedAt: { type: Date, default: null },
    revokedReason: { type: String, default: '', maxlength: API_KEY_LIMITS.REVOKE_REASON_MAX },
    revokedBy: { type: String, default: null },
    createdBy: { type: String, default: null },
    updatedBy: { type: String, default: null },
  },
  { timestamps: true },
);

apiKeySchema.index({ tenantId: 1, status: 1 });

apiKeySchema.plugin(tenantScope);
apiKeySchema.plugin(softDelete);
apiKeySchema.plugin(paginate);
apiKeySchema.plugin(optimisticConcurrency);
apiKeySchema.plugin(audit, { module: 'api_keys' });

export const ApiKeySchema = apiKeySchema;
export const ApiKey = mongoose.model(MODEL_NAME, apiKeySchema);
export default ApiKey;